version: '3.8'
services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "6541:5432"


  stats-server:
    build:
      context: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker

#  ewm-service:
#    build:
#      context: ./ewm-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
