services:
  stats-server:
    image: stats-server
    build:
      context: ./stats-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1

  ewm-service:
    image: ewm-service
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  main-db:
    image: postgres:16.1
