services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "6541:5432"

  stats-server:
    build:
      context: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db

  ewm-service:
    build:
      context: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - db
