services:
  stats-server:
    build:
      context: ./stats-server
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "6541:5432"

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
