services:
  stats-server:
    build:
      context: ./stats-server
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "6541:5432"


#  ewm-service:
#    build:
#      context: ./stats-server
#    ports:
#      - "8080:8080"

  ewm-db:
    image: postgres:16.1
